# Generated by Django 2.2.4 on 2019-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20190822_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
